language: node_js
node_js:
   - "0.10"

services:
  - couchdb

script: 
  - make

notifications:
  #webhooks: 
    #urls:
    #  - https://medic.slack.com/services/hooks/travis?token=xcYT8yusfEdSwLskhBxK4Vwj
    #on_success: change
    #on_failure: always
  #email:
  #  recipients:
  #    - milan@medicmobile.org

